export const GLOBAL_INTERVAL = 1000;
export const AUTOSAVE_INTERVAL = 10000;

export const POKER_PADS_BASE_PRICE = 400;
export const POKER_PADS_PRICE_MULTIPLIER = 1.15;

export const CURSORS_BASE_PRICE = 15;
export const CURSORS_PRICE_MULTIPLIER = 1.15;

export const CROUPIERS_BASE_PRICE = 100;
export const CROUPIERS_PRICE_MULTIPLIER = 1.15;
